version: '3.1'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    networks:
      - default
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=sensors
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    volumes:
      - influxdb-storage:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    networks:
      - default
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - default
    ports:
      - "3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana

  mosquitto:
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      restart: always
      networks:
        - default
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

volumes:
  influxdb-storage:
  grafana-storage: